/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#031428',
        'surface-dim': '#031428',
        'surface-bright': '#2a3a4f',
        'surface-container-lowest': '#000f22',
        'surface-container-low': '#0b1c30',
        'surface-container': '#1E293B',
        'surface-container-high': '#1b2b3f',
        'surface-container-highest': '#26364b',
        'surface-variant': '#26364b',
        'surface-deep': '#020D1A',
        'on-surface': '#d3e3ff',
        'on-surface-variant': '#bdc8cf',
        'inverse-surface': '#d3e3ff',
        'inverse-on-surface': '#213146',
        'outline': '#879299',
        'outline-variant': '#3e484e',
        'primary': '#68d3ff',
        'on-primary': '#003546',
        'primary-container': '#1da4d0',
        'on-primary-container': '#003546',
        'inverse-primary': '#006684',
        'secondary': '#ffb690',
        'on-secondary': '#552100',
        'secondary-container': '#ec6a06',
        'on-secondary-container': '#4a1c00',
        'tertiary': '#b9c8de',
        'on-tertiary': '#233143',
        'tertiary-container': '#8a99ae',
        'on-tertiary-container': '#233142',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'grid-line': 'rgba(148, 163, 184, 0.12)',
        'data-white': '#FFFFFF',
        patricio: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc7fb',
          400: '#38a8f8',
          500: '#00D4FF',
          600: '#0284c7',
          700: '#090979',
          800: '#03042C',
          900: '#020024',
        },
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        cunia: ['Cunia', 'Space Grotesk', 'sans-serif'],
        space: ['Space Grotesk', 'sans-serif'],
        mono: ['IBM Plex Sans', 'monospace'],
        'data-mono': ['IBM Plex Sans', 'monospace'],
        'label-caps': ['IBM Plex Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
      spacing: {
        compact: '0.5rem',
        standard: '1rem',
        relaxed: '1.5rem',
        gutter: '1rem',
        'margin-mobile': '1rem',
        'max-width': '1280px',
      },
    },
  },
  plugins: [],
}
