/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#031428',
        'surface-dim': '#031428',
        'surface-bright': '#2a3a4f',
        'surface-container-lowest': '#000f22',
        'surface-container-low': '#0b1c30',
        'surface-container': '#1E293B',
        'surface-container-high': '#1b2b3f',
        'surface-container-highest': '#26364b',
        'surface-variant': '#26364b',
        'surface-deep': '#020D1A',
        'on-surface': '#d3e3ff',
        'on-surface-variant': '#bdc8cf',
        'inverse-surface': '#d3e3ff',
        'inverse-on-surface': '#213146',
        'outline': '#879299',
        'outline-variant': '#3e484e',
        'primary': '#0081A7',
        'primary-container': '#0081A7',
        'secondary': '#2E97C2',
        'secondary-container': '#2E97C2',
        'tertiary': '#F07127',
        'tertiary-container': '#F07127',
        'neutral-light': '#F0F2F5',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#0081A7',
        'grid-line': 'rgba(148, 163, 184, 0.15)',
        'data-white': '#FFFFFF',
        patricio: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc7fb',
          400: '#2E97C2',
          500: '#0081A7',
          600: '#006c8c',
          700: '#00546d',
          800: '#03042C',
          900: '#020024',
        },
      },
      fontFamily: {
        hanken: ['"Hanken Grotesk"', 'sans-serif'],
        inter: ['"Hanken Grotesk"', 'Inter', 'sans-serif'],
        sans: ['"Hanken Grotesk"', 'sans-serif'],
        cunia: ['Cunia', '"Hanken Grotesk"', 'sans-serif'],
        space: ['Space Grotesk', '"Hanken Grotesk"', 'sans-serif'],
        mono: ['IBM Plex Sans', 'monospace'],
        'data-mono': ['IBM Plex Sans', 'monospace'],
        'label-caps': ['"Hanken Grotesk"', 'IBM Plex Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
      spacing: {
        compact: '0.5rem',
        standard: '1rem',
        relaxed: '1.5rem',
        gutter: '1rem',
        'margin-mobile': '1rem',
        'max-width': '1280px',
      },
    },
  },
  plugins: [],
}
